# params.yml

# Filenames for the final outputs
concated_filename: "data/concated.h5ads"
peakmat_filename: "data/peakmat.h5ad"

# The list of sample‐names (one per line)
atac_names_filename: "data/atac_names.txt"
test_atac_names_filename: "data/test_snapatac2_files.csv"
